-- AlterTable
ALTER TABLE `User` MODIFY `email` VARCHAR(191) NULL,
    MODIFY `firstName` VARCHAR(191) NULL,
    MODIFY `lastName` VARCHAR(191) NULL,
    MODIFY `fullName` VARCHAR(191) NULL,
    MODIFY `address` VARCHAR(191) NULL;
