export enum Role {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
}
export enum Status {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELED = 'CANCELED',
  FINISHED = 'FINISHED',
}
export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}
export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}
export enum Degree {
  DOCTOR_OF_MEDICINE = 'DOCTOR_OF_MEDICINE',
  RESIDENT_DOCTOR = 'RESIDENT_DOCTOR',
  FIRST_DEGREE_SPECIALIST = 'FIRST_DEGREE_SPECIALIST',
  SECOND_DEGREE_SPECIALIST = 'SECOND_DEGREE_SPECIALIST',
  MASTER = 'MASTER',
  PHD = 'PHD',
  ASSOCIATE_PROFESSOR = 'ASSOCIATE_PROFESSOR',
  PROFESSOR = 'PROFESSOR',
}
export enum ConditionType {
  DISEASE = 'DISEASE',
  ALLERGY = 'ALLERGY',
  SYMPTOM = 'SYMPTOM',
  PAST_SURGERY = 'PAST_SURGERY',
  FAMILY_HISTORY = 'FAMILY_HISTORY',
  OTHER = 'OTHER',
}
